apiVersion: v1
kind: Pod

metadata:
  name: pod
  namespace: coder
  labels:
    name: test
spec:
  containers:
  - name: test-container
    image: bitbull/webserver
    ports:
    - containerPort: 80 
